name: 'Build and publish Docker Image to GitHub Registry'
description: 'GitHub Action to publish Docker Images to GitHub Registry'
inputs:
  github-token:
    description: 'GitHub token to push Docker image to GitHub Packages'
    required: true
  image-name:
    description: 'Docker Image name'
    required: true
  image-tag:
    description: 'Docker Image tag'
    default: "latest"
    required: false
  extract-git-tag:
    description: 'Extract git-tag from repository'
    default: "false"
    required: false
  use-git-branch-as-tag:
    description: 'Use the git-branch-name as docker-tag'
    default: "false"
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.image-name }}
    - ${{ inputs.image-tag }}
    - ${{ inputs.extract-git-tag }}
    - ${{ inputs.use-git-branch-as-tag }}
branding:
  icon: 'box'
  color: 'blue'
